### ISSUE TITLE
Focus style not showing

### ISSUE THREAD

**Issue by KatkaVaughan** [OutcoderSoftware/AirlockBrowser#7]
Giving focus to an HTML element, such as an input field, button, or link brings that element into focus but the style is not shown. The style is shown after tapping the page anywhere and refreshing the page.

**Comment by DVaughan** [comment]
Fixed in version [2.6.1](https://github.com/OutcoderSoftware/AirlockBrowser/releases/tag/v2.6.1)
This appears to be an Android webview issue for which I have applied a work-around.
